### ISSUE TITLE
Convert the XXXX million people to a format that is more readable  

### ISSUE THREAD

**Issue by krishabbashyal** [SumanSubedi9/GeoGlance#7]
![image](https://github.com/user-attachments/assets/aa740df2-c1ad-4e96-9d54-f1097fbba219)

**Comment by SumanSubedi9** [comment]
Thank you Krishab!, The problem should be resolved now 
![Screenshot 2024-09-30 at 10 57 32 PM](https://github.com/user-attachments/assets/b32006f3-93ec-4122-b237-808588d1c885)

**Comment by krishabbashyal** [comment]
Can i see the PR that resolved this issue?
